// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  productSidebar: [{type: 'autogenerated', dirName: 'product'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
  releaseNotesSidebar: [{type: 'autogenerated', dirName: 'release-notes'}],
};

export default sidebars;
