name: Test

on:
  pull_request:

jobs:
  test:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check translations are up to date
        run: npm run i18n:check

      - name: Build website
        run: npm run build
